spring.application.name=unicorn-journey-assistant
server.servlet.context-path=/journey-assistant
server.port=8080

#LLM configuration
langchain4j.community.dashscope.chat-model.model-name=qwen-plus-latest
langchain4j.community.dashscope.chat-model.api-key=sk-2bae2c3bbee346ed839c6dad36a88a7a
#Stream Model
langchain4j.community.dashscope.streaming-chat-model.model-name=qwen-plus-latest
langchain4j.community.dashscope.streaming-chat-model.api-key=sk-2bae2c3bbee346ed839c6dad36a88a7a

#Google Gemini
#langchain4j.community.dashscope.chat-model.model-name=gemini-2.5-pro
#langchain4j.community.dashscope.chat-model.api-key=AIzaSyDxySH9-KCJb1F9Ec2SSMeqyb0jdEKd3yA

logging.level.dev.langchain4j=DEBUG

#???????????
doubao.app.id=1726338816
doubao.sst.host=https://openspeech.bytedance.com/api/v3/auc/bigmodel
doubao.app.accesstoken=wTdcVuW3TcsceaWYrOKu_xkYYKwTAezx
doubao.sst.resource.id=volc.bigasr.auc_turbo