spring.application.name=unicorn-journey-assistant
server.servlet.context-path=/journey-assistant
server.port=8080

#LLM configuration
langchain4j.community.dashscope.chat-model.model-name=qwen3-max-preview
langchain4j.community.dashscope.chat-model.api-key=sk-2bae2c3bbee346ed839c6dad36a88a7a
#Stream Model
langchain4j.community.dashscope.streaming-chat-model.model-name=qwen3-max-preview
langchain4j.community.dashscope.streaming-chat-model.api-key=sk-2bae2c3bbee346ed839c6dad36a88a7a
#embedding
#langchain4j.community.dashscope.embedding-model.api-key=sk-2bae2c3bbee346ed839c6dad36a88a7a
#langchain4j.community.dashscope.embedding-model.model-name=text-embedding-v4

#Google Gemini
#langchain4j.community.dashscope.chat-model.model-name=gemini-2.5-pro
#langchain4j.community.dashscope.chat-model.api-key=AIzaSyDxySH9-KCJb1F9Ec2SSMeqyb0jdEKd3yA

logging.level.dev.langchain4j=DEBUG

#火山引擎豆包大模型
doubao.app.id=1726338816
doubao.sst.host=https://openspeech.bytedance.com/api/v3/auc/bigmodel
doubao.app.accesstoken=wTdcVuW3TcsceaWYrOKu_xkYYKwTAezx
doubao.sst.resource.id=volc.bigasr.auc_turbo
doubao.voice.type=zh_female_cancan_mars_bigtts
doubao.voice.endpoint=wss://openspeech.bytedance.com/api/v3/tts/unidirectional/stream
doubao.voice.endpoint2=wss://openspeech.bytedance.com/api/v3/tts/bidirection



# MCP服务器配置
#mcp.server.url=http://localhost:8002/unicorn-journey-assistant/system/rpc
mcp.refund.sse-url=http://localhost:8002/unicorn-journey-assistant/system/mcp/refund/check
mcp.rednode.sse-url=http://127.0.0.1:18060/mcp

#deepseek
deepseek.base-url=https://api.deepseek.com
deepseek.api-key=sk-d1cdeff51b17440089f5860dc6c1d04e
deepseek.model-name=deepseek-chat



spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

app.parse.maxTextLength=1000000
app.parse.ocrEnabled=true
app.parse.ocrLanguages=chi_sim+eng
